#!/usr/bin/python

s= 'CATAAAATGTAGTTCTCATATGCTGCCACCGCATCAGCAGGTTAGTTTACAAATAAAAATGGTCTTACTCAACCATCCATAACGTTCGTATTCAGTAGACGAGTGCCGCAGTCTTCATTTCCATTCACCCATATATATGCCCGCTGGACATCCGGGGCAGAACGACCGCAATGTTCCTCCGGCTGCGATAATTTACGATAACTATTTAGGTTTAGCTTGCTATCTTTAGGTATCACGGCTGTTGAATACCCTATCAATCATCAGTGCAGTTCCGTCCCTTTGTCGCCCAGTGAAGGAGTCTCAGGAATGAAGACTAGTCGATGGTTTCCCCCCTATCATGCCTGGCTTACTTTGGTGACGGATCGTGAGGATACTTGATAACGCCGGGTTGCTCGGGCGCTCCGATTTGAATTTATGGGTCCCGGTGGACAATGCCTATTTGGAGCTCTGAGATGGACGTTACCTAGGCATCGCTCAATCTTCGTAGTGACCCGTACCGCTCTTCACTTCCACTGGCTAACTGTGGATACCTACTAGGGCCCCCTGTTTTGGATGCCCCACCACCGAGCTCAAGTGCACAACACCGCTCGTCTACTATGTGTTATTACTGACCGAACTCTTGAAAGAGCTCATCACGTTGAAAATAACACGTATGGCCCTAGCACATACTTAGCTGTCTTATTGGAGTCTTGTACATGACCGATGTGTCTAAGTCATCGGAGAAGACAACTTCTTAGCCACGTTCTGAAGCTTTAATATACCAGTGATTGGACCACCAAATGCCGCTTTTCAGAATAGCACCCCGGTCTTGGTCAAGTTATGTAGCCGGTAATAACTATGCGTGTTAAGACAGATGATGTCCGTATAAAACTGCCTACAGTATTGCACTTGACGGGGCAAGCCGGTGCTAGAG';
countOfA=0;
countOfC=0;
countOfG=0;
countOfT=0;
for i in s:
    if i == 'A':
        countOfA += 1;
    elif i == 'C':
        countOfC += 1;
    elif i == 'G':
        countOfG += 1;
    else:
        i == 'T';
        countOfT += 1;
print (countOfA, countOfC, countOfG, countOfT);

